version: "3.9"

services:
  user-service:
    container_name: ms-user-service
    build:
      context: .
      dockerfile: build/docker/Dockerfile
    env_file:
      - .env
    ports:
      - "8082:8080"
    depends_on:
      - postgres
      - rabbitmq
      - nats
    networks:
      - ms-user-service

  postgres:
    container_name: ms-user-postgres
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - ms-user-service

  rabbitmq:
    container_name: ms-user-rabbitmq
    image: rabbitmq:3.12-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - ms-user-service

  nats:
    container_name: ms-user-nats
    image: nats:2.10-alpine
    command: ["-js"]
    ports:
      - "4222:4222"
      - "8222:8222"
    networks:
      - ms-user-service

  nginx:
    container_name: ms-user-nginx
    image: nginx:1.25-alpine
    depends_on:
      - user-service
    volumes:
      - ./build/docker/nginx/nginx.conf.tmpl:/etc/nginx/templates/default.conf.template:ro
    env_file:
      - .env
    ports:
      - "8002:80"
    networks:
      - ms-user-service

networks:
  ms-user-service:
    driver: bridge

volumes:
  pgdata:
